theme = "blowfish"
baseURL = "https://posei.me/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-XXXXXXXXX"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagiantion]
pagetSize = 20

