languageCode = "en"
languageName = "English"
weight = 1
title = "Posei Site"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Posei's personal site"
dateFormat = "2 January 2006"

["params.author"]
name = "Posei"
headline = "how hungry"

[[params.author.links]]
github = "https://github.com/poseiso"

[[params.author.links]]
email = "mailto:contact@posei.me"

