[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Poems"
pageRef = "poems"
identifier = "U00lIUIkWk"
weight = 15

[[main]]
name = "About"
pageRef = "about"
weight = 20

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 15
